// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9b5329839558a78550bf078c3e5f323c2f0f3b86/react-helmet/index.d.ts
declare module "react-helmet" {
  // Type definitions for react-helmet
  // Project: https://github.com/nfl/react-helmet
  // Definitions by: Evan Bremer <https://github.com/evanbb>, Isman Usoh <https://github.com/isman-usoh>
  // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
  // TypeScript Version: 2.1

  /// <reference types="react" />

  import * as React from "react";

  namespace ReactHelmet {
    function Helmet(): ReactHelmet.Helmet.HelmetComponent;
    namespace Helmet {
      function peek(): ReactHelmet.Helmet.HelmetData;
      function rewind(): ReactHelmet.Helmet.HelmetData;

      interface HelmetProps {
        base?: any;
        defaultTitle?: string;
        htmlAttributes?: any;
        link?: Array<any>;
        meta?: Array<any>;
        script?: Array<any>;
        style?: Array<any>;
        title?: string;
        titleTemplate?: string;
        onChangeClientState?: (newState: any) => void;
      }

      interface HelmetData {
        base: HelmetDatum;
        htmlAttributes: HelmetDatum;
        link: HelmetDatum;
        meta: HelmetDatum;
        script: HelmetDatum;
        style: HelmetDatum;
        title: HelmetDatum;
      }

      interface HelmetDatum {
        toString(): string;
        toComponent(): React.Component<any, any>;
      }

      class HelmetComponent extends React.Component<HelmetProps, any> {}
    }
  }

  export = ReactHelmet;
}
