stages:
  - build
  - release

image: jonaskello/docker-and-compose:1.12.1-1.8.0

before_script:
  - docker login -u laurensrietveldci -p ${REGISTRY_PW}
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

build:
  stage: build
  script:
  - ./bin/ci/build

release:
  stage: release
  script:
    - ./bin/ci/release
