version: '3'
services:
  facetcheck:
    restart: unless-stopped
    image: registry.triply.cc/triply/facetcheck
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: ["app:dev"]
    environment:
      - FACETCHECK_DEV=true
    volumes:
      - ../:/home/facetcheck/node
    ports:
     - "5000:5000"
