// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-parse-link-header/64f33657616845723a7062ce636ac375a257d2e9/src/index.d.ts
declare module "parse-link-header" {
  namespace parseLinkHeader {
    export interface Link {
      url: string;
      rel: string;
      [queryParam: string]: string;
    }

    export interface Links {
      [rel: string]: Link;
    }
  }

  function parseLinkHeader(linkHeader: string): parseLinkHeader.Links;
  export = parseLinkHeader;
}
