// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/abd91fedd2b8b44babcbff1cea5a634e468ebd10/react-router-bootstrap/index.d.ts
declare module "react-router-bootstrap" {
  // Type definitions for react-router-bootstrap 0.23
  // Project: https://github.com/react-bootstrap/react-router-bootstrap
  // Definitions by: Vincent Lesierse <https://github.com/vlesierse>, Karol Janyst <https://github.com/LKay>
  // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
  // TypeScript Version: 2.1

  export { default as LinkContainer } from "react-router-bootstrap/lib/LinkContainer";
  export { default as IndexLinkContainer } from "react-router-bootstrap/lib/IndexLinkContainer";
}
