// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/e8357a2f9dee02d39138923cb6d5db544e996927/react-bootstrap/react-bootstrap.d.ts
declare module "react-leaflet" {
    // Import React
    import React = require("react");


    type Position = [number,number];
    interface MapProps {
      zoom?:number,
      center?: Position
    }
    class Map extends React.Component<MapProps, {}> {}
    interface TileLayerProps {
      url:string,
      attribution?: string
    }
    class TileLayer extends React.Component<TileLayerProps, {}> {}

    class Popup extends React.Component<{}, {}> {}

    interface MarkerProps {
      position: Position
    }
    class Marker extends React.Component<MarkerProps, {}> {}
}
